# Generated by Django 4.0.6 on 2022-07-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
    ]
